import type { Product, Banner } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Huile d\'Argan Pure BIO',
    inci: 'Argania Spinosa Kernel Oil',
    seller: 'Unica Cosmétiques',
    price: 150,
    moq: 1,
    stock: 120,
    category: 'Huiles Végétales',
    description: 'Huile d\'argan 100% pure et biologique, pressée à froid. Idéale pour les soins de la peau et des cheveux.',
    longDescription: 'Notre huile d\'argan biologique est certifiée ECOCERT et provient des coopératives de femmes de la région d\'Essaouira. Riche en vitamine E et en acides gras essentiels, elle est reconnue pour ses propriétés hydratantes, anti-âge et réparatrices. Parfaite pour les formulations de crèmes, sérums et huiles de soin.',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 5,
    reviewCount: 42,
    certifications: ['ECOCERT', 'BIO'],
  },
  {
    id: '2',
    name: 'Beurre de Karité Brut',
    inci: 'Butyrospermum Parkii Butter',
    seller: 'Unica Cosmétiques',
    price: 60,
    moq: 5,
    stock: 300,
    category: 'Beurres Végétaux',
    description: 'Beurre de karité brut, non raffiné, pour une nutrition intense de la peau.',
    longDescription: 'Directement importé du Ghana, notre beurre de karité est produit de manière traditionnelle pour conserver toutes ses vitamines et nutriments. Excellent pour les baumes à lèvres, les crèmes pour le corps et les soins capillaires pour cheveux secs.',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4,
    reviewCount: 28,
  },
  {
    id: '3',
    name: 'Hydrolat de Rose de Damas',
    inci: 'Rosa Damascena Flower Water',
    seller: 'Unica Cosmétiques',
    price: 85,
    moq: 1,
    stock: 80,
    category: 'Hydrolats',
    description: 'Hydrolat pur obtenu par distillation de pétales de roses de Damas fraîches.',
    longDescription: 'Notre hydrolat de rose est un excellent tonique pour le visage, apaisant les peaux sensibles et irritées. Il apporte un parfum délicat et luxueux à vos lotions, brumes et nettoyants visage.',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 5,
    reviewCount: 51,
    certifications: ['BIO'],
  },
  {
    id: '4',
    name: 'Gel d\'Aloe Vera Natif',
    inci: 'Aloe Barbadensis Leaf Juice',
    seller: 'Unica Cosmétiques',
    price: 45,
    moq: 2,
    stock: 250,
    category: 'Actifs Cosmétiques',
    description: 'Gel d\'aloe vera natif, riche en polysaccharides, pour une hydratation et une cicatrisation optimales.',
    longDescription: 'Extrait de feuilles fraîches d\'aloe vera cultivées en Tunisie, ce gel est un ingrédient polyvalent pour les soins après-soleil, les gels hydratants et les sérums apaisants. Sa concentration élevée en actifs garantit une efficacité maximale.',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4,
    reviewCount: 35,
  },
    {
    id: '5',
    name: 'Huile Essentielle de Lavande Fine',
    inci: 'Lavandula Angustifolia Oil',
    seller: 'Unica Cosmétiques',
    price: 250,
    moq: 0.1,
    stock: 50,
    category: 'Huiles Essentielles',
    description: 'Huile essentielle de lavande fine AOP de Provence, aux propriétés relaxantes et purifiantes.',
    longDescription: 'Distillée à la vapeur d\'eau à partir de lavande fine cultivée en haute altitude, cette huile essentielle est réputée pour son parfum complexe et ses vertus thérapeutiques. Idéale pour les produits de spa, les soins relaxants et les formulations anti-acné.',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 5,
    reviewCount: 60,
    certifications: ['AOP'],
  },
  {
    id: '6',
    name: 'Cire d\'Abeille Blanche en Pépites',
    inci: 'Cera Alba',
    seller: 'Unica Cosmétiques',
    price: 55,
    moq: 1,
    stock: 400,
    category: 'Cires & Épaississants',
    description: 'Cire d\'abeille blanche purifiée en pépites, facile à fondre et à doser.',
    longDescription: 'Notre cire d\'abeille est récoltée localement et filtrée pour obtenir une couleur blanche et une odeur neutre, tout en conservant ses propriétés protectrices et émulsifiantes. Parfaite pour les baumes, les sticks et les crèmes.',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4,
    reviewCount: 19,
  },
  {
    id: '7',
    name: 'Acide Hyaluronique (Poudre)',
    inci: 'Sodium Hyaluronate',
    seller: 'Unica Cosmétiques',
    price: 900,
    moq: 0.05,
    stock: 10,
    category: 'Actifs Cosmétiques',
    description: 'Poudre d\'acide hyaluronique de bas poids moléculaire pour une hydratation en profondeur.',
    longDescription: 'Un actif anti-âge puissant, notre acide hyaluronique pénètre profondément dans l\'épiderme pour hydrater, repulper la peau et réduire l\'apparence des rides. Idéal pour les sérums et crèmes anti-âge haute performance.',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 5,
    reviewCount: 25,
  },
  {
    id: '8',
    name: 'Extrait de Pépins de Figue de Barbarie',
    inci: 'Opuntia Ficus-Indica Seed Extract',
    seller: 'Unica Cosmétiques',
    price: 1200,
    moq: 0.5,
    stock: 5,
    category: 'Extraits Végétaux',
    description: 'Extrait précieux de pépins de figue de Barbarie, l\'un des plus puissants anti-âge naturels.',
    longDescription: 'Riche en vitamine E et en stérols, cet extrait est exceptionnellement efficace pour lutter contre les radicaux libres, atténuer les rides et raffermir la peau. Un ingrédient de luxe pour les soins contour des yeux et les élixirs de jeunesse.',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 5,
    reviewCount: 15,
    certifications: ['BIO'],
  },
];

export const mockBanners: Banner[] = [
  {
    id: 'banner-1',
    title: 'Découvrez la nouvelle Lux Cream Unica',
    description: 'Une expérience anti-âge et illuminatrice inspirée par la Méditerranée. Disponible dès maintenant.',
    imageUrl: 'https://i.postimg.cc/zXNRLp9j/Copie-de-Made-with-Poster-My-Wall-1.jpg',
    linkUrl: '/products',
    buttonText: 'Acheter maintenant',
  },
  {
    id: 'banner-2',
    title: 'Promotion sur le Beurre de Karité Brut',
    description: 'Profitez de -15% sur notre beurre de karité brut pour toute commande supérieure à 50kg.',
    imageUrl: 'https://placehold.co/1200x400.png',
    linkUrl: '/products/2',
    buttonText: 'Profiter de l\'offre',
  },
  {
    id: 'banner-3',
    title: 'Unica Link : Votre Partenaire Qualité',
    description: 'Nous nous engageons à vous fournir des matières premières tracées et certifiées.',
    imageUrl: 'https://placehold.co/1200x400.png',
    linkUrl: '#why-us',
    buttonText: 'En savoir plus',
  },
];
